// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type User struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type UserJoin struct {
	ID        int64
	UserID    string
	GuildID   string
	ChannelID string
	JoinedAt  time.Time
	LeftAt    sql.NullTime
}
